name: CI

on:
  push:
    branches: main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v4
        with:
            node-version: 20

      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build

      - name: Add Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: ':wrench: ci'
          add: |
            'dist/index.js'